checkpoint:
  mode: min
  monitor: val_loss
  save_top_k: 3
  verbose: true
data:
  image: D:\Yuliia_data\Yuliia_data\lits\img
  label: D:\Yuliia_data\Yuliia_data\lits\seg
  num_class: 3
  root_dir: D:\Yuliia_data\Yuliia_data\lits\
inference:
  augmentation:
  - monai.transforms.LoadImaged:
      args: []
      kwargs:
        keys:
        - image
  - monai.transforms.AddChanneld:
      args: []
      kwargs:
        keys:
        - image
  - monai.transforms.ResizeD:
      args: []
      kwargs:
        keys:
        - image
        mode:
        - trilinear
        spatial_size:
        - 256
        - 256
        - 64
  - monai.transforms.ScaleIntensityRanged:
      args: []
      kwargs:
        a_max: 250
        a_min: -175
        b_max: 1.0
        b_min: 0.0
        clip: true
        keys:
        - image
  - monai.transforms.ToTensorD:
      args: []
      kwargs:
        keys:
        - image
lightning:
  accumulate_grad_batches: 1
  fast_dev_run: false
  gpus: 1
  gradient_clip_val: 0
  log_every_n_steps: 1
  max_epochs: 500
  num_sanity_val_steps: 1
log:
  name: 3DYNetAG_final_review_full_dataset
  save_dir: Review_1
loss:
  monai.losses.DiceCELoss:
    args: []
    kwargs:
      softmax: true
      to_onehot_y: num_classes
net:
  models.3DYNetAttention_finalversion.YNet_Attention_3D:
    args: []
    kwargs:
      n_class: 3
optimizer:
  torch.optim.Adam:
    args: []
    kwargs:
      lr: 0.0001
      weight_decay: 0.0001
packages:
  matplotlib: 3.4.2
  monai: 0.8.0
  numpy: 1.21.1
  pytorch_lightning: 1.4.0
  sys: 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]
  torch: 1.9.0
train:
  augmentation:
  - monai.transforms.LoadImaged:
      args: []
      kwargs:
        keys:
        - image
        - label
  - monai.transforms.AddChanneld:
      args: []
      kwargs:
        keys:
        - image
        - label
  - monai.transforms.SpacingD:
      args: []
      kwargs:
        keys:
        - image
        - label
        mode:
        - bilinear
        - nearest
        pixdim:
        - 1.5
        - 1.5
        - 2.0
  - monai.transforms.Orientationd:
      args: []
      kwargs:
        axcodes: RAS
        keys:
        - image
        - label
  - monai.transforms.ScaleIntensityRanged:
      args: []
      kwargs:
        a_max: 250
        a_min: -175
        b_max: 1.0
        b_min: 0.0
        clip: true
        keys:
        - image
  - monai.transforms.ResizeD:
      args: []
      kwargs:
        keys:
        - image
        - label
        mode:
        - trilinear
        - nearest
        spatial_size:
        - 256
        - 256
        - 64
  - monai.transforms.RandFlipd:
      args: []
      kwargs:
        keys:
        - image
        - label
        prob: 0.2
        spatial_axis:
        - 0
  - monai.transforms.RandFlipd:
      args: []
      kwargs:
        keys:
        - image
        - label
        prob: 0.2
        spatial_axis:
        - 1
  - monai.transforms.RandFlipd:
      args: []
      kwargs:
        keys:
        - image
        - label
        prob: 0.2
        spatial_axis:
        - 2
  - monai.transforms.RandRotate90d:
      args: []
      kwargs:
        keys:
        - image
        - label
        max_k: 3
        prob: 0.2
  - monai.transforms.RandShiftIntensityd:
      args: []
      kwargs:
        keys:
        - image
        offsets: 0.2
        prob: 0.5
  - monai.transforms.ToTensorD:
      args: []
      kwargs:
        keys:
        - image
        - label
valid:
  augmentation:
  - monai.transforms.LoadImaged:
      args: []
      kwargs:
        keys:
        - image
        - label
  - monai.transforms.AddChanneld:
      args: []
      kwargs:
        keys:
        - image
        - label
  - monai.transforms.SpacingD:
      args: []
      kwargs:
        keys:
        - image
        - label
        mode:
        - bilinear
        - nearest
        pixdim:
        - 1.5
        - 1.5
        - 2.0
  - monai.transforms.Orientationd:
      args: []
      kwargs:
        axcodes: RAS
        keys:
        - image
        - label
  - monai.transforms.ScaleIntensityRanged:
      args: []
      kwargs:
        a_max: 250
        a_min: -175
        b_max: 1.0
        b_min: 0.0
        clip: true
        keys:
        - image
  - monai.transforms.CropForegroundd:
      args: []
      kwargs:
        keys:
        - image
        - label
        source_key: image
  - monai.transforms.ResizeD:
      args: []
      kwargs:
        keys:
        - image
        - label
        mode:
        - trilinear
        - nearest
        spatial_size:
        - 256
        - 256
        - 64
  - monai.transforms.ToTensorD:
      args: []
      kwargs:
        keys:
        - image
        - label
